### PR TITLE
Add CSS support specifying container height

### PR DESCRIPTION
**Pull request by tgallacher**
## What
Add support to the `layout` key for specifying the CSS `height` property of the root container, `<grid-layout>` custom component. 

Users can now do something like: 

```yaml
- type: custom:grid-layout
    layout:
      height: 100%
      ...
```

## Why?

I am trying to make a layout where a "footer" is permanently fixed at the bottom of the screen, regardless of how much content is in the content area. The simplest way to achieve this is by ensuring the base container -- the custom HTML element -- takes the full height of the panel. 

But, as this component doesn't expose this -- or a similar styling option -- and isn't compatible with the [card_mod](https://github.com/thomasloven/lovelace-card-mod) custom component, then we need to expose this directly. 

Example of layout with the above change:

image

## Notes

- I have also added a separate change to default the custom HTML component to display as a "block-level" element, to better mimic structure -like HTML elements, such as `div`, `section`, `main`, etc. 
- I have made the new _height_ layout property optional instead of the default to avoid potentially breaking the wide range of uses this component is likely deployed

### CODE REVIEW

**Comment by tgallacher** [comment]
cc @thomasloven 🙏

**Comment by Drealine** [comment]
Hi,

How can I set this mannualy please ?

**Comment by tgallacher** [comment]
> Hi,
> 
> How can I set this mannualy please ?

@Drealine Not sure of your dev background, so I'll just keep it high level at first -

To get this version manually, you would have to:

1. Check out the branch on my Github fork
2. Install the deps for the project
3. Build the project to get the JS file
4. Manually add that JS file into your HA set up using the "resources" settings

Let me know if you need more details on how this would actually look.

**Comment by thomasloven** [comment]
Hi. This is a great idea, and I really like it.
I just implemented some other functionality that lets this be done in a different way, and for the grid-based layouts too, though, so I'll rewrite your solution into that. Hope you don't mind.

It will be in the next release.

Thanks a lot, @tgallacher!

**Comment by Drealine** [comment]
Ok but what can I do that now ? Readme not give an example!

**Comment by Drealine** [comment]
Please reopen the PR, I can't find a solution to container height. @tgallacher

**Pull request closed without merging**
